trigger:
  branches:
    include:
      - main

variables:
  dockerRegistryServiceConnection: 'ilifes-acr-docker'  # Azure DevOps Docker registry connection
  imageName: 'ilifes/php-base'
  dockerfilePath: 'Dockerfile.base'
  tag: 'latest'
  containerRegistry: 'ilifesregistry.azurecr.io'  # e.g., ilifesregistry.azurecr.io

stages:
- stage: BuildBaseImage
  displayName: 'Build Base Image Stage'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker Base Image'
    pool:
      name: 'Default' # Use your self-hosted agent pool name
    steps:
    # need to list the files on pipeline workspace to debug issues
    - script: |
        echo "Listing files in the pipeline workspace:"
        ls -R $(Build.SourcesDirectory)
      displayName: 'List Files in Workspace'

    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
